export const categories = ["전체", "IT/컴퓨터", "경영/경제", "의학", "공학", "인문"]

export const mockBooks = [
    {
        id: 1,
        title: "컴퓨터 구조론",
        currentPrice: 15000,
        buyNowPrice: 25000,
        timeLeft: "2시간 전",
        location: "창곡동",
        imageUrl: "/placeholder.svg?height=200&width=200",
        isPopular: true,
        isEnding: true,
        hasAuction: true,
        comments: 2,
        likes: 3,
    },
    {
        id: 2,
        title: "경영학원론",
        currentPrice: 12000,
        buyNowPrice: 20000,
        timeLeft: "1일 전",
        location: "신흥동",
        imageUrl: "/placeholder.svg?height=200&width=200",
        isNew: true,
        hasAuction: true,
        comments: 0,
        likes: 1,
    },
    {
        id: 3,
        title: "데이터베이스 시스템",
        currentPrice: 18000,
        buyNowPrice: 30000,
        timeLeft: "3시간 전",
        location: "태평동",
        imageUrl: "/placeholder.svg?height=200&width=200",
        isPopular: true,
        hasAuction: true,
        comments: 5,
        likes: 7,
    },
    {
        id: 4,
        title: "마케팅의 원리",
        currentPrice: 10000,
        buyNowPrice: 15000,
        timeLeft: "5시간 전",
        location: "수진동",
        imageUrl: "/placeholder.svg?height=200&width=200",
        isEnding: true,
        hasAuction: true,
        comments: 1,
        likes: 2,
    },
]

